# Generated by Django 6.0.1 on 2026-02-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_resume_ai_summary_resume_comparison_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='predicted_salary',
            field=models.IntegerField(default=0),
        ),
    ]
