# Generated by Django 6.0.1 on 2026-02-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_activitylog_predicted_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='predicted_salary',
        ),
        migrations.AddField(
            model_name='resume',
            name='predicted_salary',
            field=models.IntegerField(default=0),
        ),
    ]
